spring:
  application:
    name: hong-application-common
  profiles:
    active: dev
  output:
    ansi:
      enabled: detect
  http:
    encoding:
      force: true
    multipart:
      max-file-size: 100MB    #设置上传文件的最大值,默认是1M
      max-request-size: 500MB #设置请求体的最大值

  redis:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池中的最小空闲连接
      min-idle: 50
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
    timeout: 15000

#mybatis:
#  mapper-locations: classpath:mapper/*.xml