spring:
  # redis config
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 500
      # 连接池中的最小空闲连接
      min-idle: 100
      # 连接池中的最大空闲连接
      max-idle: 500
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000

  # datasource config
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充配置，应用到上面的数据源中
    # 配置初始化大小、最小、最大
    initialSize: 1
    minIdle: 1
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 3600000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 3600000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;druid.stat.logSlowSql=true;
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  # rabbitmq config
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /  #该属性可以隔离不同的服务，例如可以设置每个服务对应的virtual-host,这样不同服务的消息可以做到相互隔离
    connection-timeout: 300000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
